WebApplication2/Areas/Admin/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;
using BulkyBook.Models;
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc.Rendering;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;

namespace WebApplication2.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {

        private readonly IUnitOfWork _db;
        public CompanyController(IUnitOfWork db)
        {
            _db = db;
            
        }
        public IActionResult Index()
        {
            
            return View();
        }

        //Get
        //資料
        public IActionResult Create()
        {           
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Company obj)
        {           
            if (ModelState.IsValid) { 
                _db.Company.Add(obj);
                _db.Save();
                TempData["success"] = "Conpany Create成功";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //編輯
        //Get
        public IActionResult Upsert(int? id)
        {
            //用ViewModel才能夠有效率的從不同Model中傳送資料給View
            //不須使用ViewBag,ViewData,TempData等
            Company company = new();
                            
            if (id == null || id == 0)
            {
                //如果沒有就Create一個新的
                //ViewBag.名字任意 把資料傳到View
                //ViewBag.CategoryList = CategoryList;
                return View(company);
            }
            else
            {
                company = _db.Company.GetFirstOrDefault(n=>n.Id==id);
                return View(company);
                //如果有就更新
            }

            
        }
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Company obj)
        {
            if (ModelState.IsValid)
            {                
                if(obj.Id == 0)
                {
                    _db.Company.Add(obj);
                    TempData["success"] = "Conpany Create 成功";
                }
                else
                {
                    _db.Company.Update(obj);
                    TempData["success"] = "Conpany Update 成功";
                }
                
                _db.Save();

                return RedirectToAction("Index");
            }
            return View(obj);
        }

        
        #region API CALLS
        public IActionResult GetAll()
        {
            var companyList = _db.Company.GetAll();
            //把資料回傳成Json格式
            return Json(new {data= companyList });
        }
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = _db.Company.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            _db.Company.Remove(obj);
            _db.Save();
            return Json(new { success = true, message = "Delete Successful" });

        }
        #endregion
    }

}

WebApplication2/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using BulkyBook.Models;
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc.Rendering;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;

namespace WebApplication2.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {

        private readonly IUnitOfWork _db;
        //取的本機的資訊
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(IUnitOfWork db,IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            
            return View();
        }

        //Get
        //資料
        public IActionResult Create()
        {           
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Product obj)
        {           
            if (ModelState.IsValid) { 
                _db.Product.Add(obj);
                _db.Save();
                TempData["success"] = "Product Create成功";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //編輯
        //Get
        public IActionResult Upsert(int? id)
        {
            //用ViewModel才能夠有效率的從不同Model中傳送資料給View
            //不須使用ViewBag,ViewData,TempData等
            ProductViewModel productVM = new()
            {
                Product = new(),
                CategoryList= _db.Category.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                CoverTypeList=_db.CoverType.GetAll().Select(i => new SelectListItem
                { 
                    Text = i.Name,
                    Value =i.Id.ToString()
                })
            };                       
            if (id == null || id == 0)
            {
                //如果沒有就Create一個新的
                //ViewBag.名字任意 把資料傳到View
                //ViewBag.CategoryList = CategoryList;
                return View(productVM);
            }
            else
            {
                productVM.Product=_db.Product.GetFirstOrDefault(n=>n.Id ==id);
                return View(productVM);
                //如果有就更新
            }

            
        }
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductViewModel obj, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                //取得wwwroot的路徑
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    //產生隨機數來當作檔名 避免上傳同名檔案時 會被覆蓋
                    string fileName = Guid.NewGuid().ToString();
                    //合併路徑 讓路徑能到達products資料夾 會加"@"是因為"\"字元式特殊字元
                    var uploads = Path.Combine(wwwRootPath, @"img\products");
                    //GetExtension() 取得file副檔名
                    var extension = Path.GetExtension(file.FileName);

                    //如果圖片存在
                    if (obj.Product.ImageUrl != null)
                    {
                        var previousImg = Path.Combine(wwwRootPath,obj.Product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(previousImg))
                        {
                            System.IO.File.Delete(previousImg);
                        }
                    }

                    //合併最終路徑 並建立圖片
                    using (var filestreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        //將傳入的圖片建立到資料夾
                        file.CopyTo(filestreams);
                    }
                    obj.Product.ImageUrl = @"img\products\" + fileName + extension;
                }
                if(obj.Product.Id == 0)
                {
                    _db.Product.Add(obj.Product);
                }
                else
                {
                    _db.Product.Update(obj.Product);
                }
                
                _db.Save();
                TempData["success"] = "Product Edit 成功";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        
        #region API CALLS
        public IActionResult GetAll()
        {
            var productList = _db.Product.GetAll(includeProperties:"Category,CoverType");
            //把資料回傳成Json格式
            return Json(new {data=productList});
        }
        [HttpDelete]     
        public IActionResult Delete(int? id)
        {
            var obj = _db.Product.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success=false,message="Error while deleting"});
            }

            var previousImg = Path.Combine(_webHostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(previousImg))
            {
                System.IO.File.Delete(previousImg);
            }
            _db.Product.Remove(obj);
            _db.Save();
            return Json(new { success = true, message = "Delete Success" });
        }
        #endregion
    }

}

WebApplication2/Areas/Customer/Controllers/EsgController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication2.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class EsgController : Controller
    {
        private readonly IUnitOfWork _UnitOfWork;
        public EsgController(IUnitOfWork unitOfWork)
        {
            _UnitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {

            return View();
        }

        #region API CALLS
        public IActionResult GetAll()
        {
            var dataList = _UnitOfWork.Esg.GetAll();
            //把資料回傳成Json格式
            return Json(new { data = dataList });
        }
        #endregion
    }
}

WebApplication2/ViewComponents/ShoppingCartViewComponent.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace WebApplication2.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claims != null)
            {
                if(HttpContext.Session.GetInt32(SD.SessionCart) != null)
                {
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
                else
                {
                    HttpContext.Session.SetInt32(SD.SessionCart, _unitOfWork.ShoppingCart.GetAll(
                        u => u.ApplicationUserId == claims.Value).ToList().Count);
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

WebApplication2/Views/Shared/Weather.cshtml
@model WeatherVM
@{
    string rain = "~/img/WeatherSVG/rain.svg";
}

<div class="container w-25">
	
    <div class="WeatherCard ">
        <div class="Location">@Model.location</div>
            <div class="Description">@Model.Description</div>
                <div class="CurrentWeather row">
                    <div class="Temperature col">@Model.oC
                        <div class="Celsius">°C </div>
                        <img src="~/img/WeatherSVG/day-cloudy.svg" width="350px" />
                    </div>       

                </div>
        <div class="AirFlow"><img src="~/img/WeatherSVG/airFlow.svg" width="50px" /> 23 m/h</div>       
        <div class="Rain"><img src="~/img/WeatherSVG/rain.svg" width="50px" /> @Model.Rain %</div>
    </div>
        

</div>

WebApplication2/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using BulkyBook.Utility
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - WebApplication2</title>
	<link rel="stylesheet" href="~/css/bootwatchTheme.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
	<link rel="stylesheet" href="~/css/DataTable.css" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

	<link rel="icon" href="~/favicon.ico" />
</head>
<body >

	<header>
			<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark ">
				<img src="~/img/ezgif.com-gif-maker.png"
                alt="Oops!!"
                width="45"
                height="45"/>
			  <div class="container-fluid">
					<a class="navbar-brand " asp-area="Customer" asp-controller="Home" asp-action="Index">The ru</a>
					<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
					  <span class="navbar-toggler-icon"></span>
					</button>
				<div class="collapse navbar-collapse" id="navbarColor02">
				  <ul class="navbar-nav me-auto ">
					<li class="nav-item">
							@*<a class="nav-link active" href="#">不知道為啥加這Home文字會往下*@
					  <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
					</li>           
					@if(User.IsInRole(SD.Role_Admin)){
						<li class="nav-item dropdown">
						  <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">內容</a>
						  <div class="dropdown-menu">
							<a class="dropdown-item " asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
							<a class="dropdown-item " asp-area="Admin" asp-controller="CoverType" asp-action="Index">CoverType</a>
							<a class="dropdown-item " asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
							<a class="dropdown-item " asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
							<a class="dropdown-item " asp-area="Identity" asp-page="/Account/Register">Create User</a>
							<a class="dropdown-item" href="https://www.dominos.com.tw/">Something else here</a>
							<div class="dropdown-divider"></div>
						  </div>
						</li>
					}				
					<li class="nav-item">
					  <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Privacy">即時氣象</a>
					</li>
					
					<li class="nav-item">
						<a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
							@await Component.InvokeAsync("ShoppingCart")
						</a>
					</li>
					
					
					<li class="nav-item">
						<a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">
							管理訂單
						</a>
					</li>

					<li class="nav-item">
						<a class="nav-link" asp-area="Customer" asp-controller="Esg" asp-action="Index">
							公司評鑑
						</a>
					</li>
				  </ul>
				  <partial name="_LoginPartial" />
					@*<form class="d-flex">
						<input class="form-control me-sm-2" type="text" placeholder="Search">
						<button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
						</form>*@
				</div>
			  </div>
		</nav>
		
	</header>
	<div @*class="container "*@>
		<main role="main" class="pb-3">
			@*使提示能夠全域*@
			<partial name="_Notification" />
			@RenderBody()
		</main>
	</div>

		  


	<footer class="footer text-muted bg-light fixed-bottom" >
		<div class="container">
			&copy; 2022 - WebApplication2 
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script src="https://cdn.tiny.cloud/1/9kk2owkr1xnpp3x466s1q2ulrqwcbh0cu2dvu6pslc1s5e97/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
	<script>
	</script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication2/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]','成功!!')
    </script>
        

}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]','錯誤~')
    </script>
}

WebApplication2/Views/Shared/_testPartialview.cshtml
@model string

<h>@Model</h>