WebApplication2/Areas/Admin/Controllers/CoverTypeController.cs
using Microsoft.AspNetCore.Mvc;
using BulkyBook.Models;
using BulkyBook.DataAccess;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;

namespace WebApplication2.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CoverTypeController : Controller
    {
        private readonly IUnitOfWork _db;
        public CoverTypeController(IUnitOfWork db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<CoverType> objCoverTypeList = _db.CoverType.GetAll();
            return View(objCoverTypeList);
        }

        //Get
        //資料
        public IActionResult Create()
        {           
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType obj)
        {           
            if (ModelState.IsValid) { 
                _db.CoverType.Add(obj);
                _db.Save();
                TempData["success"] = "CoverType Create成功";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //編輯
        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            //var categoryFromDb = _db.Categories.Find(id);//找尋想要修改的資料
            var coverTypeFromDbFirst = _db.CoverType.GetFirstOrDefault(u=>u.Id == id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);
            if(coverTypeFromDbFirst == null)
            {
                return NotFound();
            }
            //傳回目標資料給View，以利修改
            return View(coverTypeFromDbFirst);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType obj)
        {
            if (ModelState.IsValid)
            {
                _db.CoverType.Update(obj);
                _db.Save();
                TempData["success"] = "CoverType Edit成功";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //var categoryFromDb = _db.Categories.Find(id);
            var coverTypeFromDbFirst = _db.CoverType.GetFirstOrDefault(u=>u.Id == id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);
            if (coverTypeFromDbFirst == null)
            {
                return NotFound();
            }
            return View(coverTypeFromDbFirst);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.CoverType.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.CoverType.Remove(obj);
            _db.Save();
            TempData["success"] = "CoverType Delete成功";
            return RedirectToAction("Index");
        }
    }
}

WebApplication2/Areas/Admin/Views/CoverType/Create.cshtml
@model CoverType

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Creat CoverType</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<lable asp-for="Name">Name</lable>
			<input asp-for="Name" class="form-control" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Create</button>
		<a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial"/>
	}
}

WebApplication2/Areas/Admin/Views/CoverType/Delete.cshtml
@model CoverType

<form method="post" asp-action="DeletePost">
	<input asp-for="Id" hidden />@*為了按下按鈕後，能夠接收到此項目的Id*@
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Delete CoverType</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<lable asp-for="Name">Name</lable>
			<input asp-for="Name" disabled class="form-control" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
		<a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial"/>
	}
}

WebApplication2/Areas/Admin/Views/CoverType/Edit.cshtml
@model CoverType

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Edit CoverType</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<lable asp-for="Name">Name</lable>
			<input asp-for="Name" class="form-control" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Update</button>
		<a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial"/>
	}
}

WebApplication2/Areas/Admin/Views/CoverType/Index.cshtml
@model IEnumerable<CoverType>
@{
    ViewData["Title"] = "What's up!!";
}
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-warning">Category List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="CoverType" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-square"></i>&nbsp;Create New Category
            </a>
        </div>
    </div>
<br /><br />
<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                <p class="fs-5 text-primary">CoverType Name</p>
            </th>           
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width="50%">
                    @obj.Name
                </td>                
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="CoverType" asp-action="Edit" asp-route-id="@obj.Id"
                        class="btn btn-primary mx-auto"><i class="bi bi-pencil-fill"></i>Edit                           
                        </a>
                        <a asp-controller="CoverType" asp-action="Delete" asp-route-id="@obj.Id"
                        class="btn btn-danger mx-auto"><i class="bi bi-x-square"></i>Delete                           
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>